
use_frameworks! :linkage => :static
 
def node_require(script)
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
     '#{script}',
      {paths: [process.argv[1]]},
   )", __dir__]).strip
   end

# Use it to require both react-native's and this package's scripts:
 node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')
 
platform :ios, min_ios_version_supported
project 'GroupTravel.xcodeproj'  # ✅ <-- Add this line
prepare_react_native_project!
 
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end
 
target 'GroupTravel' do
  config = use_native_modules!

 
  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
 
  # Setup react-native-permissions
  setup_permissions([
    'Camera', 'PhotoLibrary', 'PhotoLibraryAddOnly', 'Notifications', 'MediaLibrary','Microphone','LocationAlways','LocationAccuracy','LocationWhenInUse'
  ])
 
  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
 